apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: login
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Abc123!
        - name: MYSQL_DATABASE
          value: tre
        - name: MYSQL_USER
          value: tre
        - name: MYSQL_PASSWORD
          value: 4linux
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql
